### ISSUE TITLE
initialize failed, please use the jdk from appdbg-JDK

### ISSUE THREAD

**Issue by wangyuan0217** [asmjmp0/AndroidRunnableJadx#1]
我从readme的连接https://github.com/asmjmp0/appdbg-JDK 下载了win的appdbg-JDK，然后配置到AndroidRunnableJADX的bin/jadx-gui里 JAVA_HOME = D:/DevTools/Java/zulu8.62.0.19-ca-jdk8.0.332-win_x64， zulu8.62.0.19-ca-jdk8.0.332-win_x64为我下载的appdbg-JDK的解压路径，然后在init的时候报错initialize failed, please use the jdk from appdbg-JDK,and clean the temp dir in jadx installed dir.
![image](https://user-images.githubusercontent.com/12730214/218907488-1ba67ffb-055d-486b-b118-b1ff416b73f4.png)
![image](https://user-images.githubusercontent.com/12730214/218907634-000ac468-008f-48d3-88dd-17c3caa5e5d6.png)
![image](https://user-images.githubusercontent.com/12730214/218907747-44b3815b-e146-47e5-9eb9-f2222936a456.png)
感谢

**Comment by asmjmp0** [comment]
如果是Windows，需要配置bin/jadx-gui.bat

**Comment by wangyuan0217** [comment]
之前是在jadx-gui里配置并用jadx-gui xxx.apk的，现在改配置JAVA_HOME在jadx-gui.bat里，同时用jadx-gui.bat xxx.apk了，但是init的时候报另外的错了啊
![image](https://user-images.githubusercontent.com/12730214/218910212-86e17777-d382-4c24-aae4-a29a924cdb0b.png)
![image](https://user-images.githubusercontent.com/12730214/218910240-4c3ef61c-1709-44e4-ba6b-94eb7dd729d0.png)

**Comment by asmjmp0** [comment]
麻烦附加上apk，我来看看

**Comment by asmjmp0** [comment]
可以清空jadx目录下的temp目录再试试。

**Comment by wangyuan0217** [comment]
还是报jdk那个错啊，我随便找的一个apk试的，地址是：https://wwut.lanzoul.com/iE0BP0nm8p9i
密码:7ao3
![image](https://user-images.githubusercontent.com/12730214/218911396-51782850-40f6-4021-b985-192f58b4d62d.png)

**Comment by asmjmp0** [comment]
1.Windows的JAVA_HOME在这设置
![image](https://user-images.githubusercontent.com/44521157/218914227-0d8fa71d-8e16-4582-a661-46ae862a8aff.png)
2.反混淆功能暂时不支持，会导致获取到错误的类名和方法名。
![image](https://user-images.githubusercontent.com/44521157/218914412-471c1ae7-1a5c-4d18-aa03-155eca56d6da.png)
3.int类型需要用Integer来传参，最后是运行的结果。
![image](https://user-images.githubusercontent.com/44521157/218914617-f6c0dfdd-ff79-40fc-8114-bc5866562097.png)

**Comment by wangyuan0217** [comment]
可以了，非常感谢！
